### ISSUE TITLE
مشکل در ریکت

### ISSUE THREAD

**Issue by asadkhalili** [mahmoud-eskandari/NumToPersian#15]
سلام دستت درد نکنه 
اقا من بر روی ریکت نصب کردم موقع اجرا این خطا رو میده:
export default Num2persian
^^^^^^

SyntaxError: Unexpected token 'export'

مشکل از کجاست؟

**Comment by mahmoud-eskandari** [comment]
مشکل کتابخانه نیست
مشکل از ورژن JS شماست

**Comment by asadkhalili** [comment]
سلام
npm version 6.14.8
node version v14.15.0
react version 17.0.2
next version 10.0.5
num2persian version 3.2.2

کد :
`
import Num2persian from 'num2persian';
function AddCredit(state) {
const changeInput = (e) => {
        let value = e.target.value;
       //console.log(Num2persian(value));
       console.log(Num2persian(1250));
    }
}
`

**Comment by asadkhalili** [comment]
باید چه ورژنی از جاوااسکریپت باشد؟

**Comment by mahmoud-eskandari** [comment]
احتمالا مشکل از babel یا هر مفسر دیگری که استفاده میکنید باشد.

کتابخانه‌ی فوق در چندین جای مختلف تست شده و مشکلی نداره
