### ISSUE TITLE
SyntaxError "Unexpected token 'export'"

### ISSUE THREAD

**Issue by reza-madani** [mahmoud-eskandari/NumToPersian#16]
I had this problem on the Nextjs, because SSR doesn't support ES6 export generally. I changed num2persian to:
`module.exports = Num2persian` and problem solved.

**Comment by pooriyapfn** [comment]
> I had this problem on the Nextjs, because SSR doesn't support ES6 export generally. I changed num2persian to: `module.exports = Num2persian` and problem solved.

Can you explain more? from where did you change? I have the similar problem.

**Comment by mahmoud-eskandari** [comment]
The SSR build is always cjs for compatibility. You can use [createRequire](https://nodejs.org/api/module.html#module_module_createrequire_filename) to load it in ESM mode.

**Comment by alivtar** [comment]
@mahmoud-eskandari , I have the same problem in NextJs v13. But I couldn't solve it. Could you please provide code sample for solving the problem with `createRequire()` ??
Thanks in advance.
