### ISSUE TITLE
مشکل در استفاده از پروتوتایپ

### ISSUE THREAD

**Issue by mustafa13760806** [mahmoud-eskandari/NumToPersian#17]
سلام ممنون بابت سورس خوبتون فقط من یک مشکل دارم اونم موقعیه که وقتی از پروتوتایپ میخوام استفاده کنم فایل اسکریپ فقط برای یک input کار میکنه و نمیشه همزمان دو input این ویژگی رو داشته باشن و اون یکی باید حتما از تابع onchange استفاده کنه
ممنون میشم راهنمایی کنید چطور مشکل رو برطرف کنم

**Comment by mahmoud-eskandari** [comment]
این باگ مربوط به کتابخانه نیست. مشکل شما در مدل استفاده از سلکتورها یا داپلیکیت بودن id آبجکتها یا ... شاید عامل این مشکل است.

**Comment by mustafa13760806** [comment]
این کد منه
<form style="text-align: center;" action=".../installment2/" method="POST">
<h3 style="color: #f94e60;">قیمت گوشی:</h3>
<input id="demo1" dir="ltr" name="number1" required="required" type="tel" placeholder="مثال 4/500/000 تومان" /> تومان
<div>
<div id="demo_out1"></div>
<script>
        onload = function () {
            var e = document.getElementById('demo1');
            e.oninput = myHandler;
            e.onpropertychange = e.oninput; // for IE8
            function myHandler() {
                document.getElementById('demo_out1').innerHTML = e.value.toPersianLetter();
            }
        };
</script>
</div>
<h3 style="color: #f94e60;">مبلغ پیش پرداخت:</h3>
<input id="demo2" onchange="document.getElementById('demo_out2').innerHTML = Num2persian(this.value)"  dir="ltr" name="number2" required="required" type="tel" placeholder="مثال 2/500/000 تومان" /> تومان
<div id="demo_out2"></div>
&nbsp;
<h3 style="color: #f94e60;">مدت اقساط:</h3>
<input name="operation_type" type="checkbox" value="6" /> 6 ماهه

<input name="operation_type" type="checkbox" value="10" /> 10 ماهه
<h3 style="color: #f94e60;">کارمزد ماهیانه:</h3>
<input checked="checked" disabled="disabled" max="5" min="5" name="number3" type="checkbox" value="5" /> 5 درصد

<input name="submit" type="submit" value="محاسبه کن" />

**Comment by mustafa13760806** [comment]
![image](https://user-images.githubusercontent.com/75061017/182015890-58ecfb8a-8490-4f07-9247-d4226016b777.png)
