### ISSUE TITLE
It calculates incorrectly after 16 digits!

### ISSUE THREAD

**Issue by ModernHooman** [mahmoud-eskandari/NumToPersian#2]
I'm not sure if it is only in my case or not but it calculates wrongly after 16 digits numbers.

For example after 16 digits it won't translate last digit :
```
NumToPersian(1000000000000001) // 16 digits
"یك بیلیارد  و یك"
// --------------
NumToPersian(10000000000000001) // 17 digits
"ده بیلیارد "
```

And after 21 digits it only translates first digit :
```
NumToPersian(1000000000000000000001)
"یك"
```

Thanks, You Rock man...

**Comment by mahmoud-eskandari** [comment]
10000000000000001
please paste your number into browser console!
You 'll see:
10000000000000000
that is not equal to your number
this bug not fully related to this project. It's a global javascript problem.
you should send it as string to get a correct return!

I'll refactor this project by Ecma script and arrow functions soon!
