### ISSUE TITLE
npm ERR! code EISGIT

### ISSUE THREAD

**Issue by sajaddp** [mahmoud-eskandari/NumToPersian#5]
<div dir="rtl">
سلام

پس از نصب پکیج در هنگام کار با `npm` مرتبا خطای `npm ERR! code EISGIT` ظاهر میشه.

```
npm ERR! path /home/.../node_modules/num2persian
npm ERR! code EISGIT
npm ERR! git /home/.../node_modules/num2persian: Appears to be a git repo or submodule.
```
لطفا موضوع رو بررسی کنید.
+
راه حل موقت حذف پوشه های `.git`  ساخته شده در `node_modules` هست:
``` rm -rf node_modules/*/.git/ ```
</div>

**Comment by mahmoud-eskandari** [comment]
با سلام
این مشکل در ورژن
۳.۱.۳
حل شد و فایل 
.npmignore
برای رفع این مشکل افزوده شد
