### ISSUE TITLE
Error in Build

### ISSUE THREAD

**Issue by mtaba** [mahmoud-eskandari/NumToPersian#7]
when npm run build this error accure : 
Failed to minify the code from this file:
    ./node_modules/num2persian/src/num2persian.js:50

**Comment by mahmoud-eskandari** [comment]
Please put your build system and configuration here

What is your ecmascript version?

**Comment by mtaba** [comment]
i use create-react-app

**Comment by mahmoud-eskandari** [comment]
I have a successful build on create-react-app now
Please update your `node`, `npm` and try again!

**Comment by mtaba** [comment]
just upgrade react-scripts
